### ISSUE TITLE
Booking API would respond with 400 status if used with curl

### ISSUE THREAD

**Issue by quarryman** [gonebusy/gonebusy-nodejs-client#13]
This is related to [https://github.com/gonebusy/gonebusy-nodejs-client/issues/12](https://github.com/gonebusy/gonebusy-nodejs-client/issues/12)

However this one corresponds to pure API call with curl without using nodejs-client

Here are the steps to reproduce
1. Using Swagger API UI to test

Go to
[http://sandbox.gonebusy.com/docs/api_sandbox#!/bookings/create_booking](http://sandbox.gonebusy.com/docs/api_sandbox#!/bookings/create_booking)

Specify  auth token

`Token xxx`

Specify body
```
{
  service_id: 7891245607,  //should use your service id
  date: '2016-01-14',
  time: '11:30',
  duration: 30
}
```

2. Using curl.
Corresponding curl request as generated by swagger
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: text/html' --header 'Authorization: Token xxx' -d '{ \ 
service_id: xxx, \ 
date: %272017-01-14%27, \ 
time: %2711:30%27, \ 
duration: 30 \ 
}' 'http://sandbox.gonebusy.com/api/v1/bookings/new'
```

It responds with 400 status. Response has headers only and no body at all.

I created this issue as it references to pure API call without using client.

**Comment by alexagranov** [comment]
I believe you are getting the 400 due to `date: '2016-01-14'` being in the past.

I just tried the following after the successful booking in #12:

`curl -X POST --header 'Content-Type: application/json' --hder 'Authorization: Token <xxx>' -d '{ "service_id": 7891245607, "date": "2017-01-14", "time": "11:30","duration": 30 }' 'http://sandbox.gonebusy.com/api/v1/bookings/new'

{"message":"422 No availability at requested Date/Time: 2017-01-14 11:30:00 UTC for Service: 7891245607"}`
